[workspace]
members = [
    "msg-store",
    "msg_store_uuid",
    "http-server-leveldb-filestorage",
    "msg_store_database_plugin",
    "msg_store_database_in_memory_plugin",
    "msg_store_database_leveldb_plugin",
    "msg_store_server_api"
]